name: tests
on: [push, pull_request]

jobs:

  tests:
    name: Tests
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with code coverage
        run: npm test -- --coverage

      - name: Checkception - Run action locally with its own coverage
        uses: ./
        with:
          report: 'coverage/clover.xml'
          required-percentage: 100
